name: Clean All ccache Cache

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Enter DELETE to confirm clearing all caches"
        required: true
        default: ""

jobs:
  clean-caches:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      
    steps:
      - name: Validate confirmation input
        if: ${{ github.event.inputs.confirm != 'DELETE' }}
        run: |
          echo "::error::You must enter DELETE to confirm the cleanup operation!"
          exit 1
          
      - name: Get and delete all caches
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            let totalDeleted = 0;
            
            // Get all caches
            const caches = await github.rest.actions.getActionsCacheList({
              owner,
              repo,
              per_page: 100
            });
            
            // Delete matching caches
            for (const cache of caches.data.actions_caches) {
              if (cache.key.startsWith('ccache-')) {
                console.log(`Deleting cache: ${cache.key}`);
                await github.rest.actions.deleteActionsCacheById({
                  owner,
                  repo,
                  cache_id: cache.id
                });
                totalDeleted++;
              }
            }
            
            return `Successfully deleted ${totalDeleted} caches`;

      - name: Reset environment
        run: |
          rm -rf $HOME/.ccache/*
          rm -rf $HOME/.ccache_6.1.57/*
          rm -rf $HOME/.ccache_6.1.75/*
          rm -rf $HOME/.ccache_6.1.118/*
          sudo apt clean
          sudo journalctl --vacuum-time=1s
          sudo rm -rf /var/log/*
          docker system prune -af || true
          sudo rm -rf /tmp/*
          echo "Container environment has been reset!"
          echo "Space after cleanup:"
          df -h
