name: Clean Repository Workflow

on:
  workflow_dispatch:
    inputs:
      clean_mode:
        description: "Cleanup Mode (amount--keep quantity, date--keep days):"
        required: true
        type: choice
        default: 'amount'
        options:
          - 'amount'
          - 'date'
      clean_to_keep:
        description: "Number of days/quantity of recent workflows to keep:"
        required: true
        type: string
        default: "0"

jobs:
  clean-workflows:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install GitHub CLI
        run: |
          sudo apt-mark hold firefox
          sudo apt-mark hold libc-bin
          sudo apt purge man-db
          sudo apt update
          sudo apt install -y jq
          type -p gh >/dev/null || sudo apt install -y gh
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh --version

      - name: Clean workflows by amount to keep
        if: ${{ github.event.inputs.clean_mode == 'amount' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo_full_name=$GITHUB_REPOSITORY
          # Get all workflows (in reverse chronological order by creation time)
          all_workflows=$(gh api -X GET "repos/$repo_full_name/actions/runs?per_page=100" | 
            jq --arg current_run "$GITHUB_RUN_ID" '.workflow_runs | map(select(.id != ($current_run | tonumber)))')
          # Calculate the actual number of workflows to keep
          total_workflows=$(echo "$all_workflows" | jq length)
          keep_count=$(( ${{ github.event.inputs.clean_to_keep }} < total_workflows ? ${{ github.event.inputs.clean_to_keep }} : total_workflows ))
          # Get the IDs of the latest workflows to keep
          keep_ids=$(echo "$all_workflows" | 
            jq -r 'sort_by(.created_at) | reverse | .[0:'$keep_count'] | .[].id')
          echo "Keeping the latest $keep_count workflows (ID: $keep_ids)"
          # Delete workflows not in the keep list
          echo "$all_workflows" | jq -r '.[] | select(.status != "in_progress" and .status != "queued") | .id' | while read id; do
            if ! grep -qw "$id" <<< "$keep_ids"; then
              echo "Deleting workflow $id"
              gh api -X DELETE "repos/$repo_full_name/actions/runs/$id" --silent
            fi
          done


      - name: Clean workflows by date to keep
        if: ${{ github.event.inputs.clean_mode == 'date'}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo_full_name=$GITHUB_REPOSITORY
          cutoff_date=$(date -d "${{ github.event.inputs.clean_to_keep }} days ago" -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Deleting all workflows older than $cutoff_date..."
          
          # Get the IDs of workflows to delete
          to_delete_ids=$(gh api -X GET "repos/$repo_full_name/actions/runs?created=<$cutoff_date&per_page=100" | 
            jq -r --arg current_run "$GITHUB_RUN_ID" '.workflow_runs[] | 
            select(.id != ($current_run | tonumber) and .status != "in_progress" and .status != "queued") | .id')
          
          for id in $to_delete_ids; do
            echo "Deleting workflow $id (created before $cutoff_date)"
            gh api -X DELETE "repos/$repo_full_name/actions/runs/$id" --silent
          done
